language: node_js
sudo: required
dist: xenial 
node_js:
  - "stable"
install:
  - npm install
  - npm install -g codecov
services:
  - postgresql
env:
  global:
    - PGPORT=5433
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
  - ./node_modules/.bin/codecov
  - npm start test