language: node_js
sudo: required
dist: xenial 
node_js:
  - "stable"
install:
  - npm install
  - npm install -g codecov
services:
  - postgresql
env:
  global:
    - PGPORT=5433
before_script:
  - sudo -u postgres psql -p 5432 -h 127.0.0.1
  - createdb -p 5432 -h 127.0.0.1 travis_ci_test
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
  - ./node_modules/.bin/codecov
  - npm start test