language: node_js
sudo: required
dist: trusty 
node_js:
  - "stable"
install:
  - npm install
  - npm install -g codecov
postgres:
  adapter: postgresql
  database: testing_db
  username: postgres

env:
  global:
    - PGPORT=5433
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
  - ./node_modules/.bin/codecov
  - npm start test